<?php
// $Id$
/**
 * @file performance_nightmare.module
 * A demonstration for solving database performance issues.
 */

/**
 * Implementation of hook_block().
 */
function performance_nightmare_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {

    case 'list':
      $block['random_users']['info'] = t('Random Users');
      return $block;

    case 'view':
      switch ($delta) {
        case 'random_users':
          return performance_nightmare_random_user_block();
          break;
      }
  }
}


/**
 * Choose 6 random accounts and present them in the block.
 */
function performance_nightmare_random_user_block() {
  $block['subject'] = t('Random Users');

 // get block contents from cache. If it's not there, build it.
  $content_cache = cache_get('performance_nightmare_users');
  if (!empty($content_cache)) {
    $content = $content_cache->data;
  }
  if (empty($content)) {
    $usernames = array();
    $result = db_query('SELECT * FROM {users} ORDER BY RAND() LIMIT 6');
    while ($account = db_fetch_object($result)) {
      $usernames[] = $account->name;
    }
    $content = theme('item_list', $usernames);
    cache_set('performance_nightmare_users', $content, 'cache', time() + 60);
  }
  $block['content'] = $content;
  return $block;
}
