<?php
// $Id$
/**
 * @file performance_nightmare.module
 * A demonstration for solving database performance issues.
 */

/**
 * Implementation of hook_block().
 */
function performance_nightmare_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {

    case 'list':
      $block['random_users']['info'] = t('Random Users');
      return $block;

    case 'view':
      switch ($delta) {
        case 'random_users':
          return performance_nightmare_random_user_block();
          break;
      }
  }
}


/**
 * Choose 6 random accounts and present them in the block.
 */
function performance_nightmare_random_user_block() {
  $block['subject'] = t('Random Users');
  $accounts = array();
  $max_uid = db_result(db_query('SELECT MAX(uid) FROM {users}'));
  $range = 100; // Number of user accounts in which to look for usernames.
  $starting_point = rand(1, $max_uid - $range);
  $result = db_query('SELECT * FROM {users} WHERE uid >= %d AND uid < %d  ORDER BY RAND() LIMIT 6', $starting_point, $starting_point + $range);

  while ($account = db_fetch_object($result)) {
    $usernames[] = $account->name;
  }

  $block['content'] = theme('item_list', $usernames);
  return $block;
}

